# Ongoing Issue See: https://github.com/uuid-rs/uuid/issues/792 & https://docs.rs/getrandom/latest/getrandom/#webassembly-support for more details.
# This configuration ensures that the getrandom crate uses the correct backend for WebAssembly.
# It is required for crates like uuid and rand to work on wasm32-unknown-unknown.
[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']